version: '3.7'
services:
    psql:
        image: postgres:12-alpine
        container_name: tripsit_db
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - psql_data:/var/lib/postgresql/data
volumes:
    psql_data:
        name: tripsit_db_data
        driver: local
